repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version (update periodically by running 'pre-commit autoupdate')
  rev: v0.6.8
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
