name: Setup Conda Environment
description: 'Setup conda with specified Python, NumPy, and SciPy versions'
inputs:
  python_version:
    description: 'Python version'
    required: true
  numpy_version:
    description: 'NumPy version'
    required: true
  scipy_version:
    description: 'SciPy version'
    required: true
  matrix_name:
    description: 'Name of the run matrix entry being used (for logging)'
    required: false
    default: ''
  exclude:
    description: 'If true, current run matrix entry should not be executed'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:

    - name: Display run details
      if: inputs.matrix_name != ''
      shell: bash -l {0}
      run: |
        echo "============================================================="
        echo "Run #${GITHUB_RUN_NUMBER}"
        echo "Run ID: ${GITHUB_RUN_ID}"
        echo "Testing: ${GITHUB_REPOSITORY}"
        echo "Triggered by: ${GITHUB_EVENT_NAME}"
        echo "Initiated by: ${GITHUB_ACTOR}"
        echo "============================================================="

    - name: Exit if this job was excluded
      if: inputs.exclude == 'true'
      uses: actions/github-script@v8
      with:
        script: core.setFailed('The ${{ inputs.matrix_name }} job was excluded from the run, exiting...');

    - name: Log inputs
      shell: bash -l {0}
      run: |
        echo "===== Composite Action Inputs ====="
        echo "matrix_name: ${{ inputs.matrix_name }}"
        echo "python_version: ${{ inputs.python_version }}"
        echo "numpy_version: ${{ inputs.numpy_version }}"
        echo "scipy_version: ${{ inputs.scipy_version }}"
        echo "exclude: ${{ inputs.exclude }}"
        echo "=================================="

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ inputs.python_version }}
        conda-remove-defaults: true
        channels: conda-forge
        channel-priority: "strict"

    - name: Install NumPy and SciPy
      shell: bash -l {0}
      run: |
        echo "============================================================="
        echo "Install NumPy and SciPy"
        echo "============================================================="
        conda install numpy=${{ inputs.numpy_version }} scipy=${{ inputs.scipy_version }} -q -y
        python -m pip install --upgrade pip