name: 'Setup OpenMDAO Pixi Environment'
description: 'Sets up Pixi with OpenMDAO environment'

inputs:
  environment:
    description: 'Pixi environment(s) to install'
    required: false
    default: 'py313'
  pixi_source:
    description: 'Source of pixi.toml to use: "local", "master", or a version like "3.42.0"'
    required: false
    default: 'master'
  frozen:
    description: 'Use frozen lock file (recommended for CI)'
    required: false
    default: 'true'
  openmdao_install_from:
    description: 'How to install OpenMDAO: pypi, github, wheel, local, local_developer, or none'
    required: false
    default: 'pypi'
  openmdao_version:
    description: 'OpenMDAO version (for PyPI and Github installs only): "" (latest) or str'
    required: false
    default: ''

runs:
  using: 'composite'
steps:
    - name: Download OpenMDAO pixi.toml if not in OpenMDAO repo
      shell: bash -l {0}
      run: |
        if [[ "${{ inputs.pixi_source }}" == "local" ]]; then
          echo "Using local pixi.toml"
          echo "PIXI_MANIFEST=pixi.toml" >> $GITHUB_ENV
        else
          # Determine the ref to use (master or version tag)
          if [[ "${{ inputs.pixi_source }}" == "master" ]]; then
            REF="master"
            echo "Downloading pixi.toml from OpenMDAO/OpenMDAO master branch"
          else
            REF="${{ inputs.pixi_source }}"
            echo "Downloading pixi.toml from OpenMDAO/OpenMDAO version $REF"
          fi

          # Download pixi.toml from the determined ref
          if curl -f -o openmdao-pixi.toml "https://raw.githubusercontent.com/OpenMDAO/OpenMDAO/$REF/pixi.toml"; then
            echo "Successfully downloaded OpenMDAO pixi.toml from $REF"
            echo "PIXI_MANIFEST=openmdao-pixi.toml" >> $GITHUB_ENV
          else
            echo "Failed to download OpenMDAO pixi.toml from $REF, falling back to local pixi.toml"
            echo "PIXI_MANIFEST=pixi.toml" >> $GITHUB_ENV
          fi
        fi

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        manifest-path: ${{ env.PIXI_MANIFEST }}
        environments: ${{ inputs.environment }}
        frozen: ${{ inputs.frozen }}
        cache: false

    - name: 'Install OpenMDAO'
      shell: bash -l {0}
      run: |
        eval "$(pixi shell-hook -e ${{ inputs.environment }})"
        echo "============================================================="
        echo "Install OpenMDAO"
        echo "============================================================="

        INSTALL_FROM="${{ inputs.openmdao_install_from }}"
        VERSION="${{ inputs.openmdao_version }}"

        case "$INSTALL_FROM" in
          pypi)
            if [[ -n "$VERSION" ]]; then
              echo "Installing OpenMDAO==$VERSION from PyPI"
              python -m pip install "openmdao==${VERSION}"
            else
              echo "Installing latest OpenMDAO from PyPI"
              python -m pip install "openmdao"
            fi
            ;;

          github)
            if [[ -n "$VERSION" ]]; then
              echo "Installing OpenMDAO@${VERSION} from GitHub"
              python -m pip install "git+https://github.com/OpenMDAO/OpenMDAO.git@${VERSION}#egg=openmdao"
            else
              echo "Installing OpenMDAO@master from GitHub"
              python -m pip install "git+https://github.com/OpenMDAO/OpenMDAO.git@master#egg=openmdao"
            fi
            ;;

          wheel)
            echo "Building wheel"
            pip wheel --no-deps .
            WHEEL=$(find openmdao-*.whl)
            echo "Installing from wheel: $WHEEL"
            python -m pip install "${WHEEL}"
            ;;

          local_developer)
            echo "Installing from local directory in developer mode"
            python -m pip install -e .
            ;;

          local)
            echo "Installing from local directory"
            python -m pip install .
            ;;

          none|"")
            echo "Skipping OpenMDAO installation"
            ;;

          *)
            echo "Error: Unknown install method '$INSTALL_FROM'"
            exit 1
            ;;
        esac

    - name: Display installed packages
      shell: bash -l {0}
      run: |
        pixi list -e "${{ inputs.invironment }}"